env: CartPole-v1                                                  # environnement
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 10
nbTest: 1
freqVerbose: 10
freqOptim: 10                                                                         # Optimisation de la politique tous les freqOptim evenements
fromFile: null
nbEpisodes: 1000
maxLengthTrain: 300
maxLengthTest: 500
memory_size: 10000
freqTransfer: 1000